name: Build Tauri App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  macos-build:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Install dependencies
      run: |
        npm install --legacy-peer-deps
        cargo install tauri-cli

    - name: Build macOS App
      run: cargo tauri build

    - name: Upload macOS Artifact
      uses: actions/upload-artifact@v3
      with:
        name: macos-app
        path: src-tauri/target/release/bundle/dmg/*.dmg

  linux-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Install dependencies
      run: |
        npm install --legacy-peer-deps
        cargo install tauri-cli
        sudo apt update
        sudo apt install -y libwebkit2gtk-4.0-dev build-essential libgtk-3-dev

    - name: Build Linux App
      run: cargo tauri build

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v3
      with:
        name: linux-app
        path: src-tauri/target/release/bundle/*.AppImage
